name: app

type: golang:1.11

hooks:
  build: ./build.sh
  deploy: ./deploy.sh

web:
  upstream:
    socket_family: tcp
    protocol: http

  commands:
    start: ./bartlett-todo serve

  locations:
    /:
      allow: true
      passthru: true
      root: static
      index: [index.html]
      expires: 1h

relationships:
  database: "todolist:mysql"

disk: 1024

dependencies:
  nodejs:
    elm: "~0.19"
    uglify-js: "~3.4"

crons:
  truncate:
    spec: '* */1 * * *'
    cmd: ./bartlett-todo truncate
